### ISSUE TITLE
Already exists

### ISSUE THREAD

**Issue by ecliptic-moon** [xFallenLight/type#1]
The codebase for this project is useless in itself, I know it's still a, probably heavy, work in progress but this viewpoint is from this very point in time.

To make matters **worse**, something like this already exists in JavaScript and is called `typeof()`. Bet you didn't consider that. Checkmate.

**Comment by ecliptic-moon** [comment]
`type()` is a Python thing lol

**Comment by whomhasfallen** [comment]
Alright, thanks for the notice. Just thought I'd do this as a fun project, didn't consider that. Thanks again, Lunar. ❤️
